### PR TITLE
Use Cirrus CI to test on FreeBSD

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
bors merge=@DilumAluthge,@giordano

**Comment by DilumAluthge** [comment]
I gotta figure out the name of the Cirrus status to put in `bors.toml`

**Comment by giordano** [comment]
Cirrus is a bit starting the jobs though :disappointed:

**Comment by DilumAluthge** [comment]
Yeah I need them too. Now I'll query the GitHub API and see what the status names are.

**Comment by DilumAluthge** [comment]
bors merge

**Comment by DilumAluthge** [comment]
bors merge-

**Comment by DilumAluthge** [comment]
bors merge=@DilumAluthge,@giordano

**Comment by DilumAluthge** [comment]
bors merge=@DilumAluthge,@giordano

**Pull request merged**
