### PR TITLE
Use Drone CI to test on ARM

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
bors merge=@DilumAluthge,@giordano

**Comment by DilumAluthge** [comment]
bors merge-

**Comment by DilumAluthge** [comment]
bors merge=@DilumAluthge,@giordano

**Comment by DilumAluthge** [comment]
bors merge-

**Comment by DilumAluthge** [comment]
bors merge=@DilumAluthge,@giordano

**Comment by DilumAluthge** [comment]
@giordano Any ideas? https://cloud.drone.io/bcbi/GitCommand.jl/2/1/2
```
ERROR: Unable to automatically install 'MbedTLS' from '/root/.julia/packages/MbedTLS_jll/wUtL4/Artifacts.toml'
```

**Comment by DilumAluthge** [comment]
bors merge=@DilumAluthge,@giordano

**Comment by DilumAluthge** [comment]
https://cloud.drone.io/bcbi/GitCommand.jl/3/1/2

@giordano Now the error seems to be a segfault:
```
GitCommand.jl: Error During Test at /drone/src/test/runtests.jl:15
  Got exception outside of a @test
  failed process: Process(`/root/.julia/artifacts/5c156c7cf88f4716683ae8b8abd9bea46b92d193/bin/git clone https://github.com/JuliaRegistries/General`, ProcessSignaled(11)) [0]
```

**Comment by giordano** [comment]
Can you test 32 bit Linux on Travis?

**Comment by DilumAluthge** [comment]
> Can you test 32 bit Linux on Travis?

Sure, what's the syntax?

**Comment by giordano** [comment]
https://discourse.julialang.org/t/32-bit-linux-julia-builds-are-now-available-on-travis-ci/27786

**Comment by giordano** [comment]
Sorry, I can't follow right now.  So, is it working on i686, x86_64, ARM64 GNU/Linux but not on ARM?

**Comment by DilumAluthge** [comment]
Linux is working on: i386 (Travis), AMD64 (Travis), Arm64 (Travis).

FreeBSD is working on whatever architecture Cirrus CI is giving me for FreeBSD.

macOS is working on AMD64 (Travis).

The 64-bit Windows binary is working on AMD64 (Travis).

The only thing that is not working is that I cannot get Travis to run the 32-bit Windows binary at all.

**Comment by DilumAluthge** [comment]
Oh also it's not working on 32-bit ARM. But Travis doesn't have 32-bit ARM so unclear how I can test it unless we get Drone working.

**Pull request closed without merging**
