### PR TITLE
Test 32-bit and 64-bit on Linux and Windows

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by giordano** [comment]
Travis has also 32 bit Windows: https://discourse.julialang.org/t/julia-is-now-available-on-travis-windows-builds/27187/18  When testing binaries I recommend testing on as many platforms as possible

**Comment by DilumAluthge** [comment]
@giordano It doesn't seem to like my config? https://travis-ci.com/bcbi/GitCommand.jl/builds/140971578/config

> jobs.include.arch: unknown value x64

**Comment by giordano** [comment]
I think there is something broken with 32-bit Windows on Travis, I can't find any working setup.  It used to work.  Alex will probably try to reach out someone in Travis after the holidays.

**Comment by DilumAluthge** [comment]
I opened issue https://github.com/bcbi/GitCommand.jl/issues/18 so that we don’t forget about this.

**Pull request merged**
