### PR TITLE
List some examples of supported platforms

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by giordano** [comment]
If you add Cirrus CI you can test FreeBSD, too

**Comment by DilumAluthge** [comment]
> If you add Cirrus CI you can test FreeBSD, too

I've never used Cirrus CI before. I'll install it on this repo. Do you have an example of a simple Julia Cirrus CI config file?

**Comment by giordano** [comment]
call this `.cirrus.yml`:
```yml
freebsd_instance:
  image: freebsd-12-0-release-amd64
task:
  name: FreeBSD
  env:
    matrix:
      - JULIA_VERSION: 1.3
      - JULIA_VERSION: nightly
  install_script:
    - sh -c "$(fetch https://raw.githubusercontent.com/ararslan/CirrusCI.jl/master/bin/install.sh -o -)"
  build_script:
    - cirrusjl build
  test_script:
    - cirrusjl test
  coverage_script:
    - cirrusjl coverage codecov coveralls
```

**Comment by giordano** [comment]
And with [Drone CI](https://cloud.drone.io/) you can test also for ARM (it's a different architecture, but operating systems is 32- and 64-bit GNU/Linux)

**Comment by DilumAluthge** [comment]
Just installed Drone. Do you have an example config?

**Comment by giordano** [comment]
`.drone.yml`:
```yml
---
kind: pipeline
name: linux - arm - Julia 1.3

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: julia:1.3
  commands:
  - "julia --project=. --check-bounds=yes --color=yes -e 'using InteractiveUtils; versioninfo(verbose=true); using Pkg; Pkg.build(); Pkg.test(coverage=true)'"

---
kind: pipeline
name: linux - arm64 - Julia 1.3

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: julia:1.3
  commands:
  - "julia --project=. --check-bounds=yes --color=yes -e 'using InteractiveUtils; versioninfo(verbose=true); using Pkg; Pkg.build(); Pkg.test(coverage=true)'"

...
```

**Comment by DilumAluthge** [comment]
bors merge

**Pull request merged**
